### PR TITLE
Add logger, endpoint and handler name to response to use in middlewares

### PR DESCRIPTION
**Pull request by stevededalus**
Add logger, endpoint and handler name to response so that these can use used in the 

`	HandleResponse(
		ctx context.Context,
		res *ServerHTTPResponse,
		shared SharedState,
	)`

methods.

### CODE REVIEW

**Comment by Raynos** [comment]
Should the middleware runner just pass the `req` in ? 

Having duplicate data fields between `req` and `res` will create confusion.

**Comment by stevededalus** [comment]
That's an option, but right now the Response object holds a reference to the Request object, so we could just expose these as methods in the response body. 

You asked me on the last diff to remove Request from HandleResponse's arguments, was the reason for that other than cleaning the interface? It does seem like sneaking the logger and endpoint properties into the request object is obfuscating some flow since zap.logger isn't request scoped.

**Comment by Raynos** [comment]
I dont remember saying removing request from HandleResponse.

To avoid duplication we can do : 

 - Add `request` to `HandleResponse()`
 - Add `Response.Request` field.

the fact that zap.logger is not request scoped is just not implemented yet, need to do it.

**Comment by stevededalus** [comment]
PTAL

**Pull request merged**
