### PR TITLE
restoring NewClientHTTPRequest and MakeTChannelRequest fn signatures for backward compatibility

### PR DESCRIPTION
**Pull request by chirayu**

### CODE REVIEW

**Comment by bishnuag** [comment]
there are test cases that passes timeoutConfig and now need to update them , one such example - https://sourcegraph.uberinternal.com/github.com/uber/zanzibar/-/blob/examples/example-gateway/endpoints/bar/bar_test.go#L58

Other can be seen in here https://github.com/uber/zanzibar/actions/runs/5377416059/jobs/9755855101?pr=880

**Comment by chirayu** [comment]
> there are test cases that passes timeoutConfig and now need to update them ,

fixed

**Comment by bishnuag** [comment]
fix lints ->  lints are failing due to the wrong ordering of imports

**Review by bishnuag — APPROVED** [review]
LGTM

**Pull request merged**
